INSERT INTO museums (place) VALUES ('Natural History Museum of Los Angeles County');
INSERT INTO museums (place) VALUES ('Museum of TolleranceLos Angeles');
INSERT INTO museums (place) VALUES ('Southwest Museum of the American Indian Los Angeles');
INSERT INTO museums (place) VALUES ('Norton Simon Museum Los Angeles');
INSERT INTO museums (place) VALUES ('Hammer Musuemm Los Angeles');
INSERT INTO museums (place) VALUES ('The Museum of Contemporay Art Los Angeles');
INSERT INTO museums (place) VALUES ('Berkley Natural History Museums');
INSERT INTO museums (place) VALUES ('Museum of the African Diaspora San Francisco');
INSERT INTO museums (place) VALUES ('The Walt Disney Family Museum San Francisco');
INSERT INTO museums (place) VALUES ('Cartoon Art Museum San Francisco');
INSERT INTO museums (place) VALUES ('Contemporary Jewish Museum San Francisco');
INSERT INTO museums (place) VALUES ('The Mexican Museum San Francisco');
INSERT INTO museums (place) VALUES ('Tenderlion Museum San Francisco');
INSERT INTO museums (place) VALUES ('International Art Musuemof America San Francisco');
INSERT INTO museums (place) VALUES ('California Academy of Sciences San Francisco');
INSERT INTO museums (place) VALUES ('Chabot Space and Science Center Oaklnd');
INSERT INTO museums (place) VALUES ('The Morgan Library and Museum New York');
INSERT INTO museums (place) VALUES ('Rubin Museum of Art New York');
INSERT INTO museums (place) VALUES ('Smithsonian Washington D.C.');
INSERT INTO museums (place) VALUES ('National Gallery of Art Washington D.C.');
INSERT INTO museums (place) VALUES ('United States Holocaust Memorial Museum Washington D.C.');
INSERT INTO museums (place) VALUES ('Museum of Fine Arts Boston');
INSERT INTO museums (place) VALUES ('The Salvador Dali Museum St. Petersburg FL');
INSERT INTO museums (place) VALUES ('The Museum of Fine Arts Houston');
INSERT INTO museums (place) VALUES ('National Museum of the American Indian Washington D.C.');
INSERT INTO museums (place) VALUES ('Philidelphia Museum of Art');
INSERT INTO museums (place) VALUES ('National Portrait Gallery Washington D.C.');
INSERT INTO museums (place) VALUES ('Frist Art Museum Nashville');
INSERT INTO museums (place) VALUES ('Musicians Jall of Fame and Museum Nashville');
INSERT INTO museums (place) VALUES ('The Parthenon Nashville');
INSERT INTO museums (place, visited) VALUES ('Los Angeles Museum of Art', true);
INSERT INTO museums (place, visited) VALUES ('California Science Center Los Angeles', true);
INSERT INTO museums (place, visited) VALUES ('The Broad Los Angeles', true);
INSERT INTO museums (place, visited) VALUES ('The Getty Center Los Angeles', true);
INSERT INTO museums (place, visited) VALUES ('The Getty Villa Los Angeles', true);
INSERT INTO museums (place, visited) VALUES ('La Brea Tar Pits Los Angeles', true);
INSERT INTO museums (place, visited) VALUES ('Orange County Musem of Art', true);
INSERT INTO museums (place, visited) VALUES ('The Bowers Museum Santa Ana ', true);
INSERT INTO museums (place, visited) VALUES ('Oakland Museum of California', true);
INSERT INTO museums (place, visited) VALUES ('San Francisco Museum of Modern Art', true);
INSERT INTO museums (place, visited) VALUES ('Asian Art Museum San Francisco', true);
INSERT INTO museums (place, visited) VALUES ('Exploratorium San Francisco', true);
INSERT INTO museums (place, visited) VALUES ('de Young Museum San Francisco', true);
INSERT INTO museums (place, visited) VALUES ('Legion of Honor San Francisco', true);
INSERT INTO museums (place, visited) VALUES ('The Museum of Art and Digital Entertainment Oakland', true);
INSERT INTO museums (place, visited) VALUES ('San Francisco Railway Museum', true);
INSERT INTO museums (place, visited) VALUES ('Whitney Museum of American Art Ney York', true);
INSERT INTO museums (place, visited) VALUES ('The Museum of Modern Art New York', true);
INSERT INTO museums (place, visited) VALUES ('American Museum of Natural History New York', true);
INSERT INTO museums (place, visited) VALUES ('The Metropolitan Museum of Art New York', true);

